import os
import re


ROOT_DIR = os.path.dirname(os.path.abspath(__file__))


MOCK_SERVER_HOST = 'http://127.0.0.1'
MOCK_SERVER_PORT = 8000

BASE_URL = f'{MOCK_SERVER_HOST}:{MOCK_SERVER_PORT}'

APPLICATIONS_ENDPOINT = '/applications'
APPLICATION_ENDPOINT = APPLICATIONS_ENDPOINT + '/{app_id}'
RESET_ENDPOINT = '/reset'

RATE_LIMIT = 5
RATE_UPDATING_PERIOD_S = 60
ALLOWABLE_RETRY_AFTER_DEVIATION_S = 10
ETAG_LENGTH = 40
AUTH_TOKEN_LENGTH = 25

ACTIVATION_MODE = 'immediate'  # or 'eventual'
ACTIVATION_DELAY_S = 1.5

AUTHORIZATION_HEADER_PATTERN = r'^Bearer .+'
WEAK_IF_MATCH_FORMAT_REGEX = re.compile(r'^W/"(\d+)"$')

NAME_FORBIDS_ACTIVATION_CODE = 'NAME_FORBIDS_ACTIVATION'
